@echo off
  :: ... (partie admin inchangée) ...

  :: Exécution des commandes
  echo Suppression de node_modules...
  rd /s /q node_modules
  echo Suppression de src-tauri/target
  rd /s /q src-tauri\target
  ::echo Nettoyage du cache npm...
  ::CALL npm cache clean --force
  echo Nettoyage termine. Reinstallation des dependances...
  CALL npm install
  echo Construction du projet avec npm run tauri dev...
  @echo on
  CALL npm run tauri dev

